// Tạo bàn cờ 64 ô với chỉ số i (hàng) và j (cột):
export const positions = [];
for (let i = 0; i < 64; i++) {
  positions.push({
    index: i,
    j: (i % 8) + 1,
    i: ~~(i / 8) + 1,
    color:
      ~~(i / 8) % 2 !== 0
        ? i % 2 === 0
          ? "black"
          : "white"
        : i % 2 === 0
        ? "white"
        : "black",
  });
}
//Các quân trắng ban đầu với vị trí i (hàng), j (cột) ban đầu:
export const baseWhiteChesses = [
  { img: "WK.png", id: 1, name: "K", color: 1, i: 1, j: 4, moves: [], turn: 0 },
  { img: "WC.png", id: 2, name: "C", color: 1, i: 1, j: 1, moves: [], turn: 0 },
  {
    img: "WC.png",
    id: 14,
    name: "C",
    color: 1,
    i: 1,
    j: 8,
    moves: [],
    turn: 0,
  },
  { img: "WE.png", id: 3, name: "E", color: 1, i: 1, j: 3, moves: [], turn: 0 },
  {
    img: "WE.png",
    id: 15,
    name: "E",
    color: 1,
    i: 1,
    j: 6,
    moves: [],
    turn: 0,
  },
  { img: "WQ.png", id: 4, name: "Q", color: 1, i: 1, j: 5, moves: [], turn: 0 },
  { img: "WS.png", id: 5, name: "S", color: 1, i: 2, j: 8, moves: [], turn: 0 },
  { img: "WH.png", id: 6, name: "H", color: 1, i: 1, j: 2, moves: [], turn: 0 },
  { img: "WH.png", id: 7, name: "H", color: 1, i: 1, j: 7, moves: [], turn: 0 },
  {
    img: "WS.png",
    id: 16,
    name: "S",
    color: 1,
    i: 2,
    j: 7,
    moves: [],
    turn: 0,
  },
  { img: "WS.png", id: 8, name: "S", color: 1, i: 2, j: 6, moves: [], turn: 0 },
  { img: "WS.png", id: 9, name: "S", color: 1, i: 2, j: 5, moves: [], turn: 0 },
  {
    img: "WS.png",
    id: 10,
    name: "S",
    color: 1,
    i: 2,
    j: 1,
    moves: [],
    turn: 0,
  },
  {
    img: "WS.png",
    id: 11,
    name: "S",
    color: 1,
    i: 2,
    j: 2,
    moves: [],
    turn: 0,
  },
  {
    img: "WS.png",
    id: 12,
    name: "S",
    color: 1,
    i: 2,
    j: 3,
    moves: [],
    turn: 0,
  },
  {
    img: "WS.png",
    id: 13,
    name: "S",
    color: 1,
    i: 2,
    j: 4,
    moves: [],
    turn: 0,
  },
];
//Các quân đen ban đầu với vị trí i (hàng), j (cột) ban đầu:
export const baseBlackChesses = [
  {
    img: "BK.png",
    id: 17,
    name: "K",
    color: 2,
    i: 8,
    j: 4,
    moves: [],
    turn: 0,
  },
  {
    img: "BC.png",
    id: 18,
    name: "C",
    color: 2,
    i: 8,
    j: 1,
    moves: [],
    turn: 0,
  },
  {
    img: "BC.png",
    id: 19,
    name: "C",
    color: 2,
    i: 8,
    j: 8,
    moves: [],
    turn: 0,
  },
  {
    img: "BE.png",
    id: 20,
    name: "E",
    color: 2,
    i: 8,
    j: 3,
    moves: [],
    turn: 0,
  },
  {
    img: "BE.png",
    id: 21,
    name: "E",
    color: 2,
    i: 8,
    j: 6,
    moves: [],
    turn: 0,
  },
  {
    img: "BQ.png",
    id: 22,
    name: "Q",
    color: 2,
    i: 8,
    j: 5,
    moves: [],
    turn: 0,
  },
  {
    img: "BS.png",
    id: 23,
    name: "S",
    color: 2,
    i: 7,
    j: 8,
    moves: [],
    turn: 0,
  },
  {
    img: "BH.png",
    id: 24,
    name: "H",
    color: 2,
    i: 8,
    j: 7,
    moves: [],
    turn: 0,
  },
  {
    img: "BH.png",
    id: 25,
    name: "H",
    color: 2,
    i: 8,
    j: 2,
    moves: [],
    turn: 0,
  },
  {
    img: "BS.png",
    id: 26,
    name: "S",
    color: 2,
    i: 7,
    j: 7,
    moves: [],
    turn: 0,
  },
  {
    img: "BS.png",
    id: 27,
    name: "S",
    color: 2,
    i: 7,
    j: 6,
    moves: [],
    turn: 0,
  },
  {
    img: "BS.png",
    id: 28,
    name: "S",
    color: 2,
    i: 7,
    j: 5,
    moves: [],
    turn: 0,
  },
  {
    img: "BS.png",
    id: 29,
    name: "S",
    color: 2,
    i: 7,
    j: 4,
    moves: [],
    turn: 0,
  },
  {
    img: "BS.png",
    id: 30,
    name: "S",
    color: 2,
    i: 7,
    j: 2,
    moves: [],
    turn: 0,
  },
  {
    img: "BS.png",
    id: 31,
    name: "S",
    color: 2,
    i: 7,
    j: 3,
    moves: [],
    turn: 0,
  },
  {
    img: "BS.png",
    id: 32,
    name: "S",
    color: 2,
    i: 7,
    j: 1,
    moves: [],
    turn: 0,
  },
];
export const allIs = [1, 2, 3, 4, 5, 6, 7, 8];
export const allJs = [1, 2, 3, 4, 5, 6, 7, 8];
